version : "3"
services:
  go:
    build: . 
    ports:
      - "8090:8090"
    volumes:
      - ./:/app
    environment:
      - PORT=8090
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=123456789
      - MONGO_DB=golang
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456789
      - MONGO_INITDB_DATABASE=golang
    ports:
      - 27017:27017
    volumes:
      - mongo-db:/data/db
    
volumes:
  mongo-db:
