version : "3"
services:
  go:
    build: . 
    ports:
      - "8091:8091"
    volumes:
      - postgres:/data/postgres
    environment:
      - PORT=8091
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=golang
      - POSTGRES_HOST=postgre
      - POSTGRES_PORT=5455
    depends_on:
      - postgre
  postgre:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=golang
    ports:
      - 5455:5432
    restart: always
    volumes:
    - postgres:/data/db
  
volumes:
  postgres: